# Generated by Django 3.0.5 on 2022-05-23 03:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('course', multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Django', 'Django'), ('RestAPI', 'RestAPI'), ('MySQL', 'MySQL')], max_length=27)),
                ('location', multiselectfield.db.fields.MultiSelectField(choices=[('Hyderabad', 'Hyderabad'), ('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Chennai', 'Chennai')], max_length=29)),
                ('start_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
